services:
  # PostgreSQL Database Service
  postgres:
    image: postgres
    container_name: users_db
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "auth"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - backend

  # Users Golang Service
  users_service:
    build:
      context: ./users
      dockerfile: Dockerfile
    container_name: users_service
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8000:8000"
    networks:
      - backend

networks:
  backend:
    driver: bridge 