// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Permission struct {
	ID        int32
	Name      string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	DeletedAt pgtype.Timestamp
}

type Role struct {
	ID          int32
	RoleName    string
	Permissions []string
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
	DeletedAt   pgtype.Timestamp
}

type User struct {
	ID          int32
	Username    string
	Email       string
	Password    string
	FirstName   pgtype.Text
	LastName    pgtype.Text
	PhoneNumber pgtype.Text
	IsActive    pgtype.Bool
	Role        int64
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
	DeletedAt   pgtype.Timestamp
}
