// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Permission struct {
	ID        int32            `json:"id"`
	Name      string           `json:"name"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
	DeletedAt pgtype.Timestamp `json:"deleted_at"`
}

type Role struct {
	ID          int32            `json:"id"`
	RoleName    string           `json:"role_name"`
	Permissions []string         `json:"permissions"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
	DeletedAt   pgtype.Timestamp `json:"deleted_at"`
}

type User struct {
	ID          int32            `json:"id"`
	Username    string           `json:"username"`
	Email       string           `json:"email"`
	Password    string           `json:"password"`
	FirstName   pgtype.Text      `json:"first_name"`
	LastName    pgtype.Text      `json:"last_name"`
	PhoneNumber pgtype.Text      `json:"phone_number"`
	IsActive    pgtype.Bool      `json:"is_active"`
	Role        int64            `json:"role"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
	DeletedAt   pgtype.Timestamp `json:"deleted_at"`
}
