apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  POSTGRES_DB: 'auth'
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM= # base64 encoded "postgres"
  POSTGRES_PASSWORD: cG9zdGdyZXM= # base64 encoded "postgres"
